-- luacheck configuration: `luacheck resources content tests tools`
std = "lua54"
max_line_length = 120
codes = true

exclude_files = { "tests/gate/_tmp/**", "dist/**", ".server/**" }

-- the server's prelude builds `node` for every resource
globals = { "node" }

files["resources/warden/server/**/*.lua"] = {
    -- the server half: `node` and the Lua 5.4 standard library
}

files["resources/warden/client/**/*.lua"] = {
    -- the client half runs in the game's LuaJIT (Lua 5.1); `node` is the client table there
    std = "luajit",
    globals = { "nodemp_wd" },
    read_globals = {
        "ui_imgui", "jsonEncode", "jsonDecode", "log", "settings", "ffi", "NodeMP", "be", "extensions",
        "core_input_categories", "core_environment",
    },
}

files["content/**/*.lua"] = {
    -- the content zip's modScript runs in the game's LuaJIT at mount time
    std = "luajit",
    read_globals = { "extensions", "log" },
}

files["resources/warden/client/warden/lang.lua"] = {
    -- generated by tools/lang-gen.lua: one line per dictionary entry
    max_line_length = false,
}

files["tests/unit/**/*.lua"] = {
    globals = { "node", "t", "WD_ROOT" },
    max_line_length = 140,
}

files["tests/gate/hooks/**/*.lua"] = {
    globals = { "node" },
}

files["tools/**/*.lua"] = {
    globals = { "node", "WD_ROOT" },
}

-- unused self (212) is fine in method-style modules
ignore = { "212/self" }
