-- warden/i18n: the panel's texts in the player's language.
--
-- The dictionary is warden/lang.lua, GENERATED by tools/lang-gen.lua from
-- the resource's lang/en.json and lang/ru.json (the ui.* and err.* codes),
-- so the panel and the server's chat lines come from the same files. The
-- language is the server's answer to hello (the player's /lang, else the
-- server default), or whatever set_lang was given.
--
--   i18n.set_lang("ru")            -- normalised: "ru-RU" -> "ru"; unknown -> "en"
--   i18n.lang() -> "en" | "ru"
--   i18n.t("ui.tab.players")       -- "Players"; a missing code shows as the code itself
--   i18n.t("err.denied", { perm = "mod.kick" })
--   i18n.error_text(error)         -- the text of a wd:reply error { code, params }

local ok, dict = pcall(require, "warden/lang")
if not ok or type(dict) ~= "table" then dict = {} end

local M = {}

M.LANGS = { "en", "ru" }
M.DICT = dict

local current = "en"

function M.normalize(lang)
    if type(lang) ~= "string" then return "en" end
    lang = lang:lower():sub(1, 2)
    if dict[lang] ~= nil then return lang end
    return "en"
end

function M.set_lang(lang)
    current = M.normalize(lang)
    return current
end

function M.lang()
    return current
end

local function interpolate(text, params)
    if type(params) ~= "table" then return text end
    return (text:gsub("{([%w_]+)}", function(key)
        local v = params[key]
        if v == nil then return "{" .. key .. "}" end
        if type(v) == "number" and v ~= math.floor(v) then return string.format("%g", v) end
        return tostring(v)
    end))
end

function M.t(code, params)
    local d = dict[current]
    local text = d and d[code]
    if text == nil and dict.en then text = dict.en[code] end
    if text == nil then return code end
    return interpolate(text, params)
end

-- the text of a wd:reply error; codes the server has no line for are shown as the code
function M.error_text(err)
    if type(err) ~= "table" then return M.t("err.internal") end
    local code = tostring(err.code or "internal")
    local params = type(err.params) == "table" and err.params or {}
    local text = M.t("err." .. code, params)
    if text == "err." .. code then text = M.t("ui.err." .. code, params) end
    if text == "ui.err." .. code then return code end
    return text
end

function M.missing(lang)
    local out = {}
    for code in pairs(dict.en or {}) do
        if dict[lang] == nil or dict[lang][code] == nil then out[#out + 1] = code end
    end
    table.sort(out)
    return out
end

return M
