"""GENERATED by sdk/tools/wiregen.py from server/include/net/Protocol.h.

Do not edit. The protocol is defined in that header, comments and all;
this is the same taxonomy for the tests to import. It used to be a hand-kept
copy, which is how the fixtures ended up a protocol version behind the code
and how UdpHello kept being documented as the token it stopped being."""
import enum

PROTO_VERSION = 22

# UDP endpoint-auth sizes. The UdpToken is reused as the per-session HMAC
# key and is never sent over UDP.
UDP_SESSION_KEY_LEN = 64
UDP_HELLO_NONCE_LEN = 16
UDP_HELLO_MAC_LEN = 32
UDP_DATAGRAM_MAC_LEN = 16
UDP_HELLO_MAC_LABEL = b"NODE-UDP-HELLO-v10"

FLAG_COMPRESSED = 0x01
FLAGS_RESERVED_MASK = 0xFE
MODS_INFO_ENCRYPTED = 0x01
PRE_AUTH_FRAME_CAP = 4 * 1024
MAX_FRAME_LENGTH = 1024 * 1024
MAX_UDP_DATAGRAM = 10240
SMALL_BODY_CAP = 4 * 1024
FILE_NAME_CAP = 1024
MAX_VEHICLE_CONFIG_JSON = 768 * 1024
FRAME_HEADER_SIZE = 7
FRAME_PAYLOAD_OVERHEAD = 3
MAX_BODY_CAP = MAX_FRAME_LENGTH - 3

class Cat(enum.IntEnum):
    HANDSHAKE = 0x01  # connection setup, liveness, UDP binding
    SESSION = 0x02  # player lifecycle and session-scoped pushes
    CONTENT = 0x03  # mod list + file delivery control
    VEHICLE = 0x04  # vehicle lifecycle, seating, authority
    STATE = 0x05  # high-rate vehicle state streams
    EVENT = 0x06  # named custom events (plugin/client API)
    COMMAND = 0x07  # game mod <-> launcher command channel (port 4444)
    MODULE = 0x08  # typed binary module<->client channel (v12)


class Handshake(enum.IntEnum):
    HELLO = 0x01  # L->S T u16 proto_version, tail:str player_name (v13; empty = server names Player<id>)
    WELCOME = 0x02  # S->L T u32 client_id
    PING = 0x03  # L->S T,U optional u64 LE stamp (v13; echoed)
    PONG = 0x04  # S->L T,U echo of the Ping body (v13; empty for un-stamped pings)
    UDP_TOKEN = 0x05  # S->L T u8[64] token (the per-session UDP MAC key)
    UDP_HELLO = 0x06  # L->S U u8[16] nonce, u8[32] mac (HMAC over the token, v10); client_id in UDP hdr
    MAP_INFO = 0x07  # S->L T tail:str map
    JOIN_WORLD = 0x08  # L->S T --
    VERIFY_REQUEST = 0x09  # S->L T u8 level (VerifyLevel), tail:str manifest_hash (v18; the reference manifest to judge against, empty unless level is Strict) (v15)
    VERIFY_REPORT = 0x0A  # L->S T u8 level_run (VerifyLevel), u8 outcome (VerifyOutcome), u32 problems, tail:str detail -- a Strict report's detail starts with "manifest=<hash>;" (v18) (v15)
    IDENTITY = 0x0B  # L->S T tail:str ticket (directory join ticket; empty = none) -- always the frame after Hello (v17)
    INTEGRITY_MANIFEST_REQUEST = 0x0C  # L->S T tail:str hash -- the launcher has no cached reference manifest with this hash and asks for its body (v18)
    INTEGRITY_MANIFEST_CHUNK = 0x0D  # S->L T u32 index, u32 total, tail:bytes part -- one slice (at most IntegrityChunkBytes) of the zstd-compressed manifest, sent in order, index 0..total-1 (v18)
    INTEGRITY_MANIFEST_DONE = 0x0E  # S->L T tail:str hash -- every chunk was sent; SHA-256 of the reassembled compressed bytes, which the launcher recomputes and compares (v18)


class Session(enum.IntEnum):
    KICK = 0x01  # S->G T,R tail:str reason
    SELF_INFO = 0x02  # S->G T,R u32 client_id, tail:str name
    PLAYER_JOINED = 0x03  # S->G T,R u32 client_id, tail:str name
    PLAYER_LEFT = 0x04  # S->G T,R u32 client_id, tail:str name
    PLAYER_LIST = 0x05  # S->G T,R u16 count, u16 max, count x { u32 id, str16 name }
    SESSION_END = 0x06  # L->G R u8 reason (SessionEndReason), tail:str detail
    CLIENT_ID = 0x07  # L->G R u32 client_id
    POLICY = 0x08  # G->S T,R u8 lock_mode (VehicleLockMode, applied to every car this player spawns; whitelist = the player), u8 flags (bit0 = others may use my cars' triggers, bit1 = others may grab my cars' nodes) -- the player's per-session preferences; stored, applied to existing spawns on change; a TriggerReq/Grab aimed at a car whose spawner cleared the bit is dropped (v21, replaces the player:policy custom event)


class Content(enum.IntEnum):
    MODS_REQUEST = 0x01  # L->S T --
    MODS_INFO = 0x02  # S->L T u8 flags (ModsInfoEncrypted), u8[32] key <iff bit0>, tail:json mods
    FILE_REQUEST = 0x03  # L->S T tail:str file_name
    FILE_BEGIN = 0x04  # S->L T u8 encrypted, u64 wire_size, u8[12] nonce <iff encrypted>; then wire_size raw bytes follow unframed
    FILE_DENY = 0x05  # S->L T u8 reason (FileDenyReason)
    SYNC_DONE = 0x06  # L->S T --
    RESOURCE_CHUNK = 0x07  # S->G T,R tail:json resource part (v1: reserved-name Event)
    RESOURCE_DONE = 0x08  # S->G T,R -- (v1: reserved-name Event)


class Vehicle(enum.IntEnum):
    SPAWN_REQ = 0x01  # G->S T,R u32 requested_gid (0 = new), tail:json config
    SPAWN = 0x02  # S->G T,R u32 gid, u32 spawner_id, str16 owner_name, str16 damage_blob, tail:json config
    SPAWN_DENY = 0x03  # S->one T,R str16 reason, tail:json config -- targeted refusal of SpawnReq (built-in MaxCars limit -> empty reason, or a vehicleSpawnRequest plugin veto -> its reason); the requester removes the just-created local vehicle (v7 added the reason)
    EDIT = 0x04  # G<->S T,R u32 gid, tail:json config
    DELETE = 0x05  # G<->S T,R u32 gid
    RESET = 0x06  # G<->S T,R u32 gid, tail:json posrot
    COUPLER = 0x07  # G<->S T,R u32 gid, tail:json
    PAINT = 0x08  # G<->S T,R u32 gid, tail:json paints array
    CAMERA = 0x09  # G<->S T,R u32 client_id, i32 gid (-1 = none)
    SEAT_CLAIM = 0x0A  # G->S T,R u32 gid, u8 kind (SeatClaimKind: 1=driver, 2=passenger, 3=leave), u32 claim_id -- transactional seat request (v8, replaces EnterReq/ExitReq)
    SEAT_VERDICT = 0x0B  # S->one T,R u32 gid, u32 claim_id, u8 result (SeatVerdictResult), u32 epoch, str16 reason -- targeted outcome of a SeatClaim (v8, replaces EnterDeny/ExitDeny + the client 5 s timeout); reason (v22) is the plugin's text on DeniedPlugin, "locked" on DeniedLocked, empty otherwise
    DRIVER = 0x0C  # S->G T,R u32 gid, u32 epoch, u32 client_id (v8 added epoch; old: 'Ob:<gid>:<cid>')
    SEAT_FREE = 0x0D  # S->G T,R u32 gid, u32 epoch (v8 added epoch; old: 'Ou:<gid>')
    AUTHORITY = 0x0E  # S->G T,R u32 gid, u32 epoch, u32 client_id (v8 added epoch; old: 'Oa:<gid>:<cid>')
    AUTH_REVOKE = 0x0F  # S->one T,R u32 gid, u32 epoch (v8 added epoch; old: 'Oq:<gid>')
    PLAYER_VEHICLE = 0x10  # S->G T,R u32 client_id, i32 gid (-1 = on foot), u8 role (SeatRole: 0=none/1=driver/2=passenger) (v9 added role; old: 'OV:<cid>:<gid>')
    RESYNC = 0x11  # S->G T,R same body as Spawn -- full-state resync push; the client force-reapplies the spawn (respawn) unless it is the local driver (v3). The trailing Driver/Authority carry the current seat epoch so a resync re-seeds it.
    RESYNC_REQ = 0x12  # G->S T,R u32 gid (0 = all vehicles) -- client asks for a full cached-state resync (v3; also the self-heal on a seat-epoch gap)
    TRIGGER = 0x13  # G<->S T,R u32 gid, tail:json controller call -- trigger/door actuation, accepted from ANY synced client; since v6 gated by the cancellable vehicleCouplerRequest builtin and echoed to ALL clients INCLUDING the sender (the presser applies on the echo, never inline) + cached (v3)
    DAMAGE_STAT = 0x14  # G->S T,R u32 gid, u32 counter -- periodic damage-version report from the sync authority; server-terminal (stored, compared, fires the vehicleDamageChanged builtin -- never relayed) (v4)
    DAMAGE_BLOB = 0x15  # G->S T,R u32 gid, u32 counter, tail:bytes blob -- RARE damage-blob upload (debounced after the counter increased); server-terminal, stored for damaged spawns/resyncs; blob capped at 60000 B so it fits the str16 redelivery field (v4)
    COUPLER_SET = 0x16  # S->G T,R u32 gid, tail:json coupler entries (same schema as Coupler) -- server-initiated coupler/door actuation, applied by EVERY client including the driver and merged into the server coupler cache (v6; moved from 0x18 in v8)
    TAG = 0x17  # S->G T,R u32 gid, str16 key, tail:str value -- one server-assigned vehicle tag pair; EMPTY value = tag removed; replayed per pair after Spawn on join/resync; never accepted from a client (v11)
    LOCK = 0x18  # S->G T,R u32 gid, u8 mode (VehicleLockMode), u16 count, count x u32 player_id (whitelist) -- vehicle lock state; gates NEW seat claims server-side (DeniedLocked); replayed after the Tag packets when mode != Unlocked; never accepted from a client (v12)
    CONFIG_HASH = 0x19  # G<->S T,R u32 gid, u32 hash -- config reconciliation marker: FNV-1a-32 over the cached config bytes as sent. S->G broadcast on every config mutation + join/resync replay; G->S periodic client report, a mismatch triggers a silent debounced targeted resync (v12)
    TRIGGER_REQ = 0x1A  # G->S T,R u32 gid, tail:json call -- ask the vehicle's SYNC AUTHORITY to execute a trigger: a controller call ({controllerName, functionName, ...}) or, since v20, an in-world trigger press ({t, a, val}; the authority tells the two apart by shape); gated by the cancellable vehicleTriggerRequest builtin + relayRequest, forwarded to the authority as a TARGETED Trigger (0x13), never cached (v12)
    NODE_GRAB = 0x1B  # G->S T,R u32 gid, u8 action (NodeGrabAction), u32 node_id, f32[3] target, f32 force -- EXPERIMENTAL node-grabber request; dropped unless [Experimental] NodeGrab is on AND the fail-closed vehicleNodeGrabRequest hook explicitly allows (v12)
    NODE_GRAB_SET = 0x1C  # S->one T,R u32 gid, u32 grabber_id, u8 action, u32 node_id, f32[3] target, f32 force -- an allowed NodeGrab forwarded to the vehicle's sync authority, which applies the grab force in its vehicle VM; server-only subtype (v12)
    GRAB = 0x1D  # G<->S T,R u32 gid (0 = about the grabber, not a car: strength preset / clear-all-pins), tail:json -- the SYNCED node grabber's stream (grab/move/release, deform snapshot, link/pin) from ANY synced client, relayed verbatim to every OTHER client like Coupler; never cached; the receiving owner enforces its own "let others grab my car" (v20, replaces the vehicle:grab custom event)
    EDIT_DENY = 0x1E  # S->one T,R u32 gid, u8 what (1 = edit, 2 = paint), str16 reason -- a vehicleEditRequest / vehiclePaintRequest plugin veto WITH a reason, sent to the initiator before the rollback (Resync / Paint) so the player learns why; nothing for a refusal without a reason (v22)


class State(enum.IntEnum):
    POS = 0x01  # G<->S U(T) binary kinematic snapshot, layout above (v5; old: 'Zp' + json until v4)
    INPUTS = 0x02  # G<->S T u32 gid, tail:json non-core input axes only since v5
    ELECTRICS = 0x03  # G<->S T u32 gid, tail:json
    NODES = 0x04  # G<->S T u32 gid, tail:json
    BREAK_GROUPS = 0x05  # G<->S T u32 gid, tail:json
    CONTROLLER = 0x06  # G<->S T u32 gid, tail:json
    POWERTRAIN = 0x07  # G<->S T u32 gid, tail:json
    ENGINE = 0x08  # G<->S T u32 gid, tail:json
    HEAD_POSE = 0x09  # G<->S U(T) binary head/camera pose, fixed 33-byte layout above; per PLAYER, not per vehicle -- never cached (v12)
    POS_BATCH = 0x0A  # S->G U several Pos bodies back to back, 72 bytes each, no framing between them (v19)
    FIRE = 0x0B  # G<->S T u32 gid, tail:json fire state from the vehicle's sync authority; relayed and cached like Electrics (v21, replaces the vehicle:fire custom event)


class Event(enum.IntEnum):
    EVENT = 0x01  # G<->S T,R str16 name, tail:bytes data


class Command(enum.IntEnum):
    KEEPALIVE = 0x01  # G<->L CC -- (echoed verbatim)
    VERSION_REQ = 0x02  # G->L CC --
    VERSION = 0x03  # L->G CC u16 proto_version
    CONNECT = 0x04  # G->L CC u16 port, tail:str host
    QUIT = 0x05  # G->L CC --
    STATUS_REQ = 0x06  # G->L CC --
    STATUS = 0x07  # L->G CC u8 state (CcStatusState), tail:str detail
    PING_REQ = 0x08  # G->L CC --
    PING = 0x09  # L->G CC i32 ms (-1 = unknown)
    MAP_REQ = 0x0A  # G->L CC --
    MAP = 0x0B  # L->G CC tail:str map (empty before a session)
    MOD_LOADED = 0x0C  # G->L CC tail:str file_name
    MOD_LIST = 0x0D  # L->G CC u16 count, count x str16 file_name
    CONNECT_FAILED = 0x0E  # L->G CC tail:str reason
    PROMPT = 0x0F  # L->G CC u8 kind (PromptKind)
    PROMPT_ANSWER = 0x10  # G->L CC u8 accept (0/1)
    AUTH = 0x11  # G->L CC,R tail:str token -- loopback auth; MUST be the first frame the game sends on BOTH the command and relay channels (wire v10). The launcher drops the connection on a missing/wrong token.
    SERVER = 0x12  # L->G CC u16 port, tail:str host -- which server this session is on. The mirror of Connect: that is the game asking to join, this is the launcher saying where it already did. Sent when a session's handshake completes, and to a game that attaches while one is running, because a launcher started from the server list (or with --server) joins WITHOUT the game ever naming the server -- and the game needs the address for its own bookkeeping, without which loading the map fails.


class Module(enum.IntEnum):
    DATA = 0x01  # G<->S T,R u32 channel_id, tail:bytes payload (v12)


# Which category each subtype enum belongs to; encode() derives the
# category byte from the class of the subtype it is given.
CATEGORY_OF = {
    Handshake: Cat.HANDSHAKE,
    Session: Cat.SESSION,
    Content: Cat.CONTENT,
    Vehicle: Cat.VEHICLE,
    State: Cat.STATE,
    Event: Cat.EVENT,
    Command: Cat.COMMAND,
    Module: Cat.MODULE,
}

SUBTYPE_ENUM = {cat: sub for sub, cat in CATEGORY_OF.items()}


# Enums for fields inside a body, rather than for packet subtypes.
class SessionEndReason(enum.IntEnum):
    DISCONNECTED = 0  # server closed the session (kick reason in detail)
    CONNECTION_LOST = 1  # transport dropped unexpectedly
    QUIT = 2  # local user quit


class FileDenyReason(enum.IntEnum):
    UNKNOWN = 0  # no such file in the content index
    PROTECTED = 1  # file is protected and this session may not fetch it
    UNREADABLE = 2  # server failed to open/read the file


class CcStatusState(enum.IntEnum):
    IDLE = 0  # old 'Ulstart'
    LOADING = 1  # old 'UlLoading...' (download progress in detail)
    DONE = 2  # old 'Uldone'
    CONNECT_FAILED = 3  # old 'UlConnection Failed! (...)'
    DISCONNECTED = 4  # old 'UlDisconnected: ...'


class PromptKind(enum.IntEnum):
    LOCAL_MODS_FOUND = 1  # old push 'WMODS_FOUND'


class SeatClaimKind(enum.IntEnum):
    DRIVER = 1  # take the driver seat (or become a passenger if it is taken)
    PASSENGER = 2  # ride as a passenger; never take the driver seat
    LEAVE = 3  # leave the vehicle (replaces the old ExitReq)


class SeatVerdictResult(enum.IntEnum):
    GRANTED_DRIVER = 0  # now the driver + sync authority of the vehicle
    GRANTED_PASSENGER = 1  # seated as a passenger (driver seat was taken / kind was passenger)
    DENIED_PLUGIN = 2  # a plugin vetoed the enter/exit via a cancellable builtin
    DENIED_OCCUPIED = 3  # refused: the claimant already drives another (non-unicycle) vehicle
    DENIED_UNICYCLE = 4  # refused: the target is another player's walking avatar
    DENIED_GONE = 5  # refused: the vehicle no longer exists
    LEFT = 6  # leave granted: the claimant is on foot now
    DENIED_LOCKED = 7  # refused: the vehicle lock denies this seat (v12, VehiclePacket::Lock)


class VehicleLockMode(enum.IntEnum):
    UNLOCKED = 0  # anyone may enter (default; the whitelist is empty)
    LOCKED_ALL = 1  # nobody may enter in any role except the whitelist
    DRIVER_ONLY = 2  # the DRIVER seat needs the whitelist; passengers ride freely


class NodeGrabAction(enum.IntEnum):
    GRAB = 1  # start pulling node_id toward target with up to `force` N
    MOVE = 2  # update the pull target of an active grab
    RELEASE = 3  # stop pulling (target/force ignored)


class SeatRole(enum.IntEnum):
    NONE = 0  # on foot (gid == -1)
    DRIVER = 1  # occupies the driver seat (and is the sync-authority candidate)
    PASSENGER = 2  # rides as a passenger (never simulates the vehicle)


class VerifyLevel(enum.IntEnum):
    OFF = 0  # the server does not ask; the launcher still applies its Size floor
    SIZE = 1  # every entry's length, plus a sweep for files added under content/
    SCRIPTS = 2  # Size, plus a content hash of the game's lua/ and ui/ trees
    FULL = 3  # hash everything, archives included (an audit, not a pre-join check)
    STRICT = 4  # Scripts, plus the archives' tables of contents against the server's reference manifest, the whole game root and the user folder (v18)


class VerifyOutcome(enum.IntEnum):
    CLEAN = 0  # the check ran and the install matches the game's own manifest
    DIFFERS = 1  # the check ran and found mismatches; `problems` counts them
    FAILED = 2  # the check could not run at all (no manifest, unreadable, malformed)
