-- lang-gen: writes resources/warden/client/warden/lang.lua -- the panel's
-- dictionary -- from resources/warden/lang/{en,ru}.json, so the client and
-- the server's chat lines come from the same files. Only the ui.* codes (the
-- panel's own labels) and the err.* codes (the wd:reply refusals the panel
-- prints) are taken; the server streams client/*.lua as they are, and a
-- .json would not reach the game. Run after editing a dictionary; CI checks
-- the file is current.
--
--   lua tools/lang-gen.lua            write the file
--   lua tools/lang-gen.lua --check    exit 1 when the file is stale

local sep = package.config:sub(1, 1)

local function script_dir()
    local src = debug.getinfo(1, "S").source
    if src:sub(1, 1) == "@" then src = src:sub(2) end
    return src:match("^(.*)[/\\][^/\\]+$") or "."
end

local root = script_dir() .. sep .. ".."
package.path = root .. sep .. "tools" .. sep .. "lib" .. sep .. "?.lua;" .. package.path
local json = require("json")

local LANG = root .. sep .. "resources" .. sep .. "warden" .. sep .. "lang" .. sep
local OUT = table.concat({ root, "resources", "warden", "client", "warden", "lang.lua" }, sep)
local LANGS = { "en", "ru" }
local TAKE = { "^ui%.", "^err%." }

local function read(path)
    local f = io.open(path, "rb")
    if not f then return nil end
    local text = f:read("a")
    f:close()
    return text
end

local function wanted(code)
    for _, p in ipairs(TAKE) do
        if code:match(p) then return true end
    end
    return false
end

-- a Lua string literal LuaJIT reads back byte for byte (UTF-8 stays as it is)
local function quote(s)
    return '"' .. s:gsub('[%c"\\]', function(c)
        if c == '"' then return '\\"' end
        if c == "\\" then return "\\\\" end
        return string.format("\\%03d", c:byte())
    end) .. '"'
end

local out = {
    "-- GENERATED by tools/lang-gen.lua from resources/warden/lang/*.json -- do not edit; edit the",
    "-- .json and run the tool. The ui.* codes are the panel's labels, the err.* codes the refusals.",
    "return {",
}
local total = 0
for _, lang in ipairs(LANGS) do
    local text = read(LANG .. lang .. ".json")
    if text == nil then
        io.stderr:write("lang-gen: cannot read " .. LANG .. lang .. ".json\n")
        os.exit(1)
    end
    local dict = json.decode(text)
    local codes = {}
    for code, line in pairs(dict) do
        if type(line) == "string" and wanted(code) then codes[#codes + 1] = code end
    end
    table.sort(codes)
    out[#out + 1] = "    " .. lang .. " = {"
    for _, code in ipairs(codes) do
        out[#out + 1] = "        [" .. quote(code) .. "] = " .. quote(dict[code]) .. ","
        total = total + 1
    end
    out[#out + 1] = "    },"
end
out[#out + 1] = "}"
local generated = table.concat(out, "\n") .. "\n"

if arg[1] == "--check" then
    local current = read(OUT)
    if current == nil then
        io.stderr:write("lang-gen: " .. OUT .. " is missing; run lua tools/lang-gen.lua\n")
        os.exit(1)
    end
    if current:gsub("\r\n", "\n") ~= generated then
        io.stderr:write("lang-gen: " .. OUT .. " is stale; run lua tools/lang-gen.lua\n")
        os.exit(1)
    end
    print(string.format("lang-gen: client/warden/lang.lua is current (%d lines)", total))
    os.exit(0)
end

local f = assert(io.open(OUT, "wb"))
f:write(generated)
f:close()
print(string.format("lang-gen: wrote %s (%d lines)", OUT, total))
